### PR TITLE
Properly fix server crash issue

### PR DESCRIPTION
**Pull request by Tslat**
Tested as working

image

Apologies for the messaround

### CODE REVIEW

**Comment by gdude2002** [comment]
Apparently I can't remember things, who knew lmao.

While we're here, what MC versions did you end up supporting? Just the 1.16.x versions, right?

**Comment by Tslat** [comment]
This PR is for 1.16.5
I have a 1.17 branch complete, but I can't merge that into your git cus you don't have a 1.17 branch yet

**Comment by gdude2002** [comment]
Gotcha, I'll get this handled now.

**Comment by gdude2002** [comment]
Thanks for that - I've created a 1.17 branch for you as well, based on the 1.16 one.

**Pull request merged**
